version: "3.8"

services:
  # PHP Service
  php:
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/html
    depends_on:
      - database
    networks:
      - atypikhouse-network

  # Database Service
  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-atypikhouse}
      POSTGRES_USER: ${DATABASE_USER:-app}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
    volumes:
      - atypikhouse-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - atypikhouse-network

  # Nginx Service
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - atypikhouse-network

  # Frontend Angular Service
# Commentez ou supprimez cette section
# frontend:
#   build:
#     context: ./frontend
#     dockerfile: Dockerfile
#   volumes:
#     - ./frontend:/app
#     - node_modules:/app/node_modules
#   ports:
#     - "4200:4200"
#   command: npm start
#   networks:
#     - atypikhouse-network

networks:
  atypikhouse-network:

volumes:
  atypikhouse-db-data:
  node_modules:
